language: python
python:
  - '3.5'

addons:
  apt:
    packages:
      - llvm-3.8-dev

env:
  - LLVM_CONFIG=/usr/bin/llvm-config-3.8

install:
  - pip install --upgrade pip wheel
  - pip install --upgrade setuptools
  - pip install -r requirements.txt
  - pip install -r requirements-ci.txt

script:
  - echo "Done"
