language: python
python:
  - '3.5'

cache: pip

env:
  - LLVM_CONFIG=/usr/bin/llvm-config-3.8

before_install:
  - sudo apt-get install llvm-3.8-dev

install:
  - pip install --upgrade pip wheel
  - pip install --upgrade setuptools
  - pip install -r requirements.txt
  - pip install -r requirements-ci.txt

script:
  - echo "Done"
